// app.js
//
// The "glue" between the interface (HTML) and the logic (hive-api.js + raffle.js).
// There's NO important computation here: we just read what the user typed,
// call the right functions, and show the result on screen.
//
// It also manages the language (English by default, with a button to switch
// to Spanish): since much of this page's content is generated by JavaScript
// (results, status messages...) instead of already being in the HTML, we
// keep the last computed data around so we can "repaint" it in the new
// language without having to ask Hive for it again.

import { getContentReplies, getBlock, getDynamicGlobalProperties } from './hive-api.js';
import { computeRaffle, filterRepliesByDeadline } from './raffle.js';
import { t, getLang, setLang, applyStaticTranslations } from './i18n.js';

// How many new blocks to add when suggesting a "future block" for the raffle.
// Hive produces a block every ~3 seconds, so 1200 blocks ≈ 1 hour.
// This gives the organizer plenty of time to publish the announcement before
// the target block exists.
const BLOQUES_DE_MARGEN = 1200;
const SEGUNDOS_POR_BLOQUE = 3;

// State we need to remember so we can redraw the screen (e.g. when the
// language changes) without calling the Hive API again.
let sorteoEnCurso = null; // { author, permlink, blockNum } of the raffle being configured
let ultimoEstadoBloque = null; // latest "can we draw yet?" result
let ultimoResultado = { crear: null, verificar: null }; // latest computed results

// Converts an <input type="datetime-local"> value (e.g. "2026-08-28T20:00")
// into a UTC ISO string (e.g. "2026-08-28T20:00:00Z"). We treat the typed
// value as UTC directly, not as the browser's local timezone — this way the
// deadline means the exact same instant for the organizer and for every
// verifier, no matter where they are.
function deadlineInputToIso(inputEl) {
  return inputEl.value ? `${inputEl.value}:00Z` : null;
}

// ---------- Language ----------

function cambiarIdioma() {
  const nuevoIdioma = getLang() === 'en' ? 'es' : 'en';
  setLang(nuevoIdioma);
  refrescarTodoElIdioma();
}

function actualizarBotonIdioma() {
  // Same as hive-scope: the button shows the flag and code of the CURRENT
  // language (not the language you'd switch to if you clicked it).
  document.getElementById('lang-flag').textContent = getLang() === 'es' ? '🇪🇸' : '🇬🇧';
  document.getElementById('lang-label').textContent = getLang().toUpperCase();
}

// Repaints everything on screen in the current language: the static text
// (via data-i18n) and also the content we generate dynamically with
// JavaScript, using the data we have stored.
function refrescarTodoElIdioma() {
  applyStaticTranslations();
  actualizarBotonIdioma();

  if (sorteoEnCurso && !document.getElementById('config-resultado').classList.contains('hidden')) {
    actualizarTextoDeCompromiso();
  }
  pintarEstadoBloque();

  if (ultimoResultado.crear) pintarResultado('resultado-crear', ultimoResultado.crear);
  if (ultimoResultado.verificar) pintarResultado('resultado-verificar', ultimoResultado.verificar);
}

// ---------- Tabs ----------

function setupTabs() {
  const botones = document.querySelectorAll('.tab-btn');
  botones.forEach((boton) => {
    boton.addEventListener('click', () => {
      document.querySelectorAll('.tab-btn').forEach((b) => b.classList.remove('active'));
      document.querySelectorAll('.tab-panel').forEach((p) => p.classList.remove('active'));

      boton.classList.add('active');
      document.getElementById(`tab-${boton.dataset.tab}`).classList.add('active');
    });
  });
}

// ---------- Step 1: Configure raffle ----------

async function handleConfigurar(evento) {
  evento.preventDefault();

  const author = document.getElementById('config-author').value.trim();
  const permlink = document.getElementById('config-permlink').value.trim();
  const deadline = deadlineInputToIso(document.getElementById('config-deadline'));

  const boton = evento.target.querySelector('button');
  boton.disabled = true;
  boton.textContent = t('btnSuggestBlockLoading');

  try {
    const props = await getDynamicGlobalProperties();
    const blockNumSugerido = props.head_block_number + BLOQUES_DE_MARGEN;

    sorteoEnCurso = { author, permlink, blockNum: blockNumSugerido, deadline };

    document.getElementById('config-blocknum').value = blockNumSugerido;
    document.getElementById('config-resultado').classList.remove('hidden');

    actualizarTextoDeCompromiso();
    await actualizarEstadoBloque();
  } catch (err) {
    alert(t('errQueryFailed', { msg: err.message }));
  } finally {
    boton.disabled = false;
    boton.textContent = t('btnSuggestBlock');
  }
}

function actualizarTextoDeCompromiso() {
  const blockNum = document.getElementById('config-blocknum').value;
  const { author, permlink, deadline } = sorteoEnCurso;

  let texto = t('commitText', { author, permlink, blockNum });
  if (deadline) {
    texto += '\n' + t('commitDeadlineLine', { deadline });
  }

  document.getElementById('config-texto').value = texto;
}

async function actualizarEstadoBloque() {
  const blockNum = Number(document.getElementById('config-blocknum').value);
  sorteoEnCurso.blockNum = blockNum;

  try {
    const props = await getDynamicGlobalProperties();
    const bloquesRestantes = blockNum - props.last_irreversible_block_num;

    if (bloquesRestantes > 0) {
      const minutosAprox = Math.ceil((bloquesRestantes * SEGUNDOS_POR_BLOQUE) / 60);
      ultimoEstadoBloque = { tipo: 'esperando', bloquesRestantes, minutosAprox };
    } else {
      ultimoEstadoBloque = { tipo: 'listo' };
    }
  } catch (err) {
    ultimoEstadoBloque = { tipo: 'error', mensaje: err.message };
  }

  pintarEstadoBloque();
}

// Renders ultimoEstadoBloque on screen, in the current language.
function pintarEstadoBloque() {
  if (!ultimoEstadoBloque) return;

  const estadoEl = document.getElementById('config-estado');
  const botonSortear = document.getElementById('btn-sortear');

  if (ultimoEstadoBloque.tipo === 'esperando') {
    estadoEl.textContent = t('statusWaiting', {
      blocks: ultimoEstadoBloque.bloquesRestantes,
      minutes: ultimoEstadoBloque.minutosAprox,
    });
    botonSortear.disabled = true;
  } else if (ultimoEstadoBloque.tipo === 'listo') {
    estadoEl.textContent = t('statusReady');
    botonSortear.disabled = false;
  } else {
    estadoEl.textContent = t('statusError', { msg: ultimoEstadoBloque.mensaje });
  }
}

// ---------- Step 2: Draw ----------

async function handleSortear() {
  const boton = document.getElementById('btn-sortear');
  boton.disabled = true;
  boton.textContent = t('btnDrawLoading');

  try {
    const { author, permlink, blockNum, deadline } = sorteoEnCurso;
    const resultado = await ejecutarSorteo(author, permlink, blockNum, deadline);

    mostrarResultado('resultado-crear', { author, permlink, blockNum, deadline, ...resultado });
  } catch (err) {
    alert(t('errDrawFailed', { msg: err.message }));
  } finally {
    boton.disabled = false;
    boton.textContent = t('btnDraw');
  }
}

// ---------- Verification ----------

async function handleVerificar(evento) {
  evento.preventDefault();

  const author = document.getElementById('verify-author').value.trim();
  const permlink = document.getElementById('verify-permlink').value.trim();
  const blockNum = Number(document.getElementById('verify-blocknum').value);
  const deadline = deadlineInputToIso(document.getElementById('verify-deadline'));
  const ganadorAnunciado = document.getElementById('verify-ganador-anunciado').value.trim();

  const boton = evento.target.querySelector('button');
  boton.disabled = true;
  boton.textContent = t('btnVerifyLoading');

  try {
    const resultado = await ejecutarSorteo(author, permlink, blockNum, deadline);

    mostrarResultado('resultado-verificar', {
      author,
      permlink,
      blockNum,
      deadline,
      ganadorAnunciado: ganadorAnunciado || null,
      ...resultado,
    });
  } catch (err) {
    alert(t('errVerifyFailed', { msg: err.message }));
  } finally {
    boton.disabled = false;
    boton.textContent = t('btnVerify');
  }
}

// Shared function: fetches the Hive data needed and computes the raffle.
// Used by BOTH "Draw now" and "Verify", to guarantee both paths do
// exactly the same thing.
async function ejecutarSorteo(author, permlink, blockNum, deadline) {
  const [replies, block] = await Promise.all([
    getContentReplies(author, permlink),
    getBlock(blockNum),
  ]);

  if (!block) {
    throw new Error(t('errBlockNotExist', { blockNum }));
  }

  const validReplies = filterRepliesByDeadline(replies, deadline);

  return computeRaffle({ replies: validReplies, block });
}

// ---------- Show results ----------

// Stores the result data (so it can be repainted if the language changes)
// and renders it on screen.
function mostrarResultado(elementId, datos) {
  if (elementId === 'resultado-crear') ultimoResultado.crear = datos;
  if (elementId === 'resultado-verificar') ultimoResultado.verificar = datos;

  pintarResultado(elementId, datos);
}

function pintarResultado(elementId, datos) {
  const { author, permlink, blockNum, deadline, blockId, participantes, ganador, ganadorAnunciado } = datos;

  const contenedor = document.getElementById(elementId);
  contenedor.classList.remove('hidden');

  let comparacionHtml = '';
  if (ganadorAnunciado) {
    const coincide = ganadorAnunciado === ganador;
    const clave = coincide ? 'resultMatch' : 'resultNoMatch';
    const clase = coincide ? 'ok' : 'error';
    comparacionHtml = `<p class="${clase}">${t(clave, { name: ganadorAnunciado })}</p>`;
  }

  const deadlineHtml = deadline
    ? `<p><strong>${t('resultDeadline')}</strong> ${deadline}</p>`
    : '';

  contenedor.innerHTML = `
    <h3>${t('resultTitle')}</h3>
    <p><strong>${t('resultPost')}</strong> @${author}/${permlink}</p>
    <p><strong>${t('resultBlockUsed')}</strong> #${blockNum}</p>
    ${deadlineHtml}
    <p><strong>${t('resultBlockId')}</strong> <code>${blockId}</code></p>
    <p><strong>${t('resultParticipants', { count: participantes.length })}</strong></p>
    <details>
      <summary>${t('resultSeeList')}</summary>
      <ol>${participantes.map((p) => `<li>${p}</li>`).join('')}</ol>
    </details>
    <p class="ganador">${t('resultWinner')} <strong>@${ganador}</strong></p>
    ${comparacionHtml}
  `;
}

// ---------- Initialization ----------

function init() {
  applyStaticTranslations();
  actualizarBotonIdioma();

  setupTabs();

  document.getElementById('lang-btn').addEventListener('click', cambiarIdioma);
  document.getElementById('form-configurar').addEventListener('submit', handleConfigurar);
  document.getElementById('config-blocknum').addEventListener('change', actualizarTextoDeCompromiso);
  document.getElementById('btn-actualizar-estado').addEventListener('click', actualizarEstadoBloque);
  document.getElementById('btn-sortear').addEventListener('click', handleSortear);
  document.getElementById('form-verificar').addEventListener('submit', handleVerificar);

  document.getElementById('btn-copiar-texto').addEventListener('click', () => {
    const textarea = document.getElementById('config-texto');
    textarea.select();
    navigator.clipboard.writeText(textarea.value);
  });
}

init();
